config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :hobbies do
    resources :events do
      resources :bookings, only: [:index, :create, :destroy]
      resources :reviews, only: [:create, :destroy]
    end
    resources :chatrooms, only: [:new, :create, :show] do
      resources :messages, only: :create
    end
  end

  resources :bookings, only: [:index, :destroy]
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :hobby
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :bookings, dependent: :destroy
  belongs_to :hobby
  has_many :reviews, dependent: :destroy
end

app/models/hobby.rb
class Hobby < ApplicationRecord
  belongs_to :user
  has_many :events, dependent: :destroy
  has_one :chatroom, dependent: :destroy

  accepts_nested_attributes_for :chatroom
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy

  def admin?
    self.admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  private

  def authenticate_admin!
    unless current_user && current_user.admin?
      redirect_to root_path, alert: "You are not authorized to perform this action."
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def new
    @event = Event.find(params[:event_id])
    @booking = Booking.new
  end

  def create
    @hobby = Hobby.find(params[:hobby_id])
    @event = @hobby.events.find(params[:event_id])
    @booking = current_user.bookings.build(event: @event)

    if @booking.save!
      redirect_to hobby_event_bookings_path, notice: 'Booking was successfully created.'
    else
      redirect_back fallback_location: root_path, alert: 'Failed to create booking.'
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy

    redirect_to bookings_path, notice: 'Booking was successfully destroyed'
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :authenticate_user!

  def show
    @hobby = Hobby.find(params[:hobby_id])
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
  end

  def new
    @hobby = Hobby.find(params[:hobby_id])
    @chatroom = Chatroom.new
    @message = Message.new
  end

  def create
    @hobby = Hobby.find(params[:hobby_id])
    @chatroom = Chatroom.new(hobby_id: @hobby.id)

    if @chatroom.save
      redirect_to hobby_chatroom_path(@hobby, @chatroom), notice: 'Chatroom was successfully created.'
    else
      render 'hobbies/show', status: :unprocessable_entity
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.where(hobby_id: params[:hobby_id])
  end

  def show
    @event = Event.find(params[:id])
    @reviews = @event.reviews
    @review = Review.new
  end

  def new
    @hobby = Hobby.find(params[:hobby_id])
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.hobby_id = params[:hobby_id]
    if @event.save
      redirect_to hobby_event_path(@event.hobby_id, @event), notice: 'Event was successfully created!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @hobby = Hobby.find(params[:hobby_id])
    @event = Event.find(params[:id])
  end

  def update
    @hobby = Hobby.find(params[:hobby_id])
    @event = Event.find(params[:id])
    @event.update(event_params)
    redirect_to hobby_events_path
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to hobby_events_path, notice: 'Event was deleted.'
  end

  private

  def event_params
    params.require(:event).permit(:name, :location, :date, :time)
  end
end

app/controllers/events_index_controller.rb
class EventsIndexController < ApplicationController
end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :create, :destroy]

  def index
    @hobbies = Hobby.all
  end

  def show
    @hobby = Hobby.find(params[:id])
    @events = Event.where(hobby_id: params[:id])
  end

  def new
    @hobby = Hobby.new
    @hobby.build_chatroom
  end

  def create
    @hobby = Hobby.new(hobby_params)
    @hobby.user = current_user
    if @hobby.save
      redirect_to hobbies_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @hobby = Hobby.find(params[:id])
    @hobby.destroy
    redirect_to hobbies_path, status: :see_other
  end

  private

  def hobby_params
    params.require(:hobby).permit(:name, chatroom_attributes: [:name])
  end
end

app/controllers/home_index_controller.rb
class HomeIndexController < ApplicationController
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @hobby = Hobby.find(params[:hobby_id])
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    if @message.save
      ChatroomChannel.broadcast_to(
        @chatroom,
        render_to_string(partial: "message", locals: { message: @message })
      )
      head :ok
    else
      render "chatrooms/show", status: :unprocessable_entity
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def index
    @reviews = Review.all
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @event = Event.find(params[:event_id])
    @review = Review.new
  end

  def create
    @hobby = Hobby.find(params[:hobby_id])
    @event = @hobby.events.find(params[:event_id])
    @review = current_user.reviews.build(review_params.merge(event: @event))
    if @review.save
      redirect_to hobby_event_path(@event.hobby_id, @event), notice: "Review was added successfully!"
    else
      redirect_back fallback_location: root_path, alert: 'Failed to create review.'
    end
  end

  def destroy
    @hobby = Hobby.find(params[:hobby_id])
    @event = @hobby.events.find(params[:event_id])
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to hobby_event_path(@event.hobby_id, @event), notice: 'Booking was successfully destroyed'
  end

  private

  def review_params
    params.require(:review).permit(:comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<%# <div class="back-btn"> %>
  <%# <%= link_to "Back to Events", hobby_event_bookings_path(@event, @bookings), class: "btn btn-dark btn-sm mb-4" %>
<%# </div> %>
<div class="container">

  <h1>Upcoming Events</h1>

  <div class="booking-list mt-4">
    <div>
      <% @bookings.each do |booking| %>
        <div class="mt-4 border-bottom border-dark" style="width: 400px;">
          <p><strong>Hobby:</strong> <%= booking.event.hobby.name %></p>
          <p><strong>Event:</strong> <%= booking.event.name %> - <%= booking.event.date.strftime("%A, %B %d") %></p>
          <div class="d-flex mb-4">
            <%= link_to "See more", hobby_event_path(booking.event.hobby, booking.event), class: "btn rounded-pill me-2 btn-info btn-sm" %>
            <%= button_to "Remove", hobby_event_booking_path(booking.event.hobby, booking.event, booking), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "btn rounded-pill btn-dark btn-sm" %>

          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<%# <div class="booking-form mt-4 style="width:24rem"></div> %>

app/views/chatrooms/new.html.erb
<div class="form-chat mt-4">
  <%= simple_form_for [@hobby, @chatroom] do |f| %>
    <%= f.input :name,
    placeholder: @hobby.name %>
    <%= f.button :submit, class: "btn btn-light btn-sm" %>
   <% end %>
</div>

app/views/chatrooms/show.html.erb
<div class="container chatroom-bg">

<div class="back-btn mt-2">
  <%= link_to "Back to hobby", hobby_path(params[:hobby_id]), class: "btn btn-outline-dark rounded-pill btn-sm mb-4" %>
</div>


<div class="container chatroom" data-controller="chatroom-subscription"
  data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>">
  <h1 style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;"><%= @chatroom.name %></h1>

  <div class="container messages" data-chatroom-subscription-target="messages">
    <% @chatroom.messages.each do |message| %>
      <%= render "messages/message", message: message %>
    <% end %>
  </div>

  <div class="container-messages justify-content-between align-items-center">
    <%= simple_form_for [@hobby, @chatroom, @message], html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" }, class: "d-flex" } do |f| %>
      <%= f.input :content,
        label: false,
        placeholder: "Type your message here...",
        wrapper_html: {class: "flex-grow-1"}
      %>
      <div class="send-btn">
      <%= f.submit "Send", class: "btn btn-dark rounded-pill mb-3" %>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/events/edit.html.erb
<div class="event-form mt-4" style="width: 24rem">



  <%= simple_form_for [@hobby, @event] do |f| %>
    <%= f.input :name %>
    <%= f.input :location %>
    <%= f.input :date %>
    <%= f.input :time %>
    <div class="btn btn-light btn-sm rounded-pill">
      <%= f.button :submit %>
    </div>
  <% end %>

</div>

app/views/events/index.html.erb
<%# all events %>
<div class="back-btn">
  <%= link_to "Back to hobby", hobby_path(params[:hobby_id]), class: "btn btn-dark btn-sm mb-4" %>
</div>

<div class="event-list">

  <% @events.each do |event| %>
    <h1 class="title mt-3"><%= event.hobby.name %></h1>
    <p><%= event.name %></p>
    <p><%= event.date %></p>

    <div class="event-btn">
      <%= link_to "See Details", hobby_event_path(event.hobby_id,event), class: "btn btn-dark btn-sm mb-4" %>

      <%= link_to "Edit", edit_hobby_event_path(event.hobby_id, event), class: "btn btn-dark btn-sm mb-4" %>

      <%= link_to "Delete", hobby_event_path(event.hobby_id, event), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger btn-sm mb-4" %>
    </div>
  <% end %>

</div>

app/views/events/new.html.erb
<%# create the event  %>
<div class="mx-auto" style="width: 800px;" >

  <div class="event-form mt-4" style="width: 24rem">
    <%= simple_form_for [@hobby, @event] do |f| %>
      <%= f.input :name %>
      <%= f.input :location %>
      <%= f.input :date %>
      <%= f.input :time %>
      <div class="btn btn-light btn-sm">
        <%= f.button :submit %>
      </div>
    <% end %>

  </div>

</div>

app/views/events/show.html.erb
<%# details of a single event %>
<div class="bg-white">
  <div class="container back-btn">
    <%= link_to "Back to hobby", hobby_path(params[:hobby_id]), class: "btn btn-dark rounded-pill btn-sm mb-4" %>
    <%# <%= link_to "Back to Events", hobby_events_path(@event.hobby), class: "btn btn-dark btn-sm mb-4" %>
  </div>

  <div class="container flex-container" style="display: flex; flex-direction: row; justify-content: space-between;">
    <div class="event" style="width: 45%;">


      <div class="card" style="bottom: 160px; height: 55%; background-image: url(https://images.unsplash.com/photo-1646038572806-3d5f4252c567?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NjR8fHB1cnBsZSUyMGFuZCUyMG9yYW5nZSUyMGdyYWRpZW50fGVufDB8fDB8fHww);">
        <div class="container">
          <div class="container card-detail mt-4">
            <h1 class="event-title"><%= @event.name %></h1>
            <p class="event-title"><%= @event.location %></p>
            <p class="event-title"><%= @event.date.strftime("%A, %B %d") %></p>
            <p class="event-title"><%= @event.time.strftime("%I:%M %p") %></p>
          </div>

          <div class="container event-btn mb-4">
            <%= link_to "Edit", edit_hobby_event_path(@event.hobby_id, @event), class: "btn btn-dark btn-sm rounded-pill mb-4" %>
            <%= link_to "Delete", hobby_event_path(@event), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-outline-danger rounded-pill btn-sm mb-4" %>
          </div>

          <div class="container join-btn mt-4">
            <% if user_signed_in? %>
              <% if current_user.bookings.exists?(event_id: @event.id) %>
                <p>This event is already booked by you.</p>
                <%= link_to "View My Events", bookings_path, class: "btn btn-outline-dark rounded-pill btn-sm" %>
              <% else %>
                <%= button_to "Add to My Events", hobby_event_bookings_path(@event.hobby, @event), class: "btn btn-dark rounded-pill btn-sm", method: :post %>
              <% end %>
            <% end %>
          </div>

        </div>


      </div>


    </div>

    <%# btn options for the user to choose action %>


    <div class="review-container" style="width: 50%;">
      <%# <%= link_to "Add a Review", new_hobby_event_review_path(@hobby.event.review) %>
      <div class="review-box">
        <h3>Reviews</h3>
        <%# Form to add a new review %>
        <% if user_signed_in? %>
          <%= form_with(model: [ @event, @review ], url: hobby_event_reviews_path(@event.hobby, @event), method: :post) do |form| %>
            <div class="field">
              <%= form.text_area :comment, placeholder: "Add a review", class: 'form-control' %>
            </div>
            <div class="submit-btn mt-2" style="align-items: right;">
              <%= form.submit "Add Review", class: "btn btn-outline-dark btn-sm rounded-pill" %>
            </div>
          <% end %>
        <% else %>
          <p>Please sign in to add a review.</p>
        <% end %>

      </div>

      <%# Display existing reviews %>
      <div class="review-list mt-4">

        <% @reviews.each do |review| %>
          <div class="review mt-4">
            <p><%= review.comment %></p>

            <div class="btn-pos" style="display: flex; flex-direction: row; align-items: flex-end; justify-content: flex-end;">
              <% if user_signed_in? && review.user == current_user %>
                <%= button_to "Delete", hobby_event_review_path(review.event.hobby, review.event, review), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "btn btn btn-outline-danger rounded-pill btn-sm" %>
              <% end %>
            </div>

          </div>
        <% end %>
      </div>


    </div>

  </div>

</div>

<%# linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),  %>

app/views/hobbies/index.html.erb
<div class="container">
  <h1 class="title mt-3">Hobbies</h1>

  <% if current_user.admin? %>
    <%= link_to "Add a hobby", new_hobby_path, class: "btn rounded-pill me-2 btn-light mb-4" %>
  <% end %>

</div>


<div class="hobby-list">
  <div class="container cards-container" style="flex-wrap: wrap; gap: 1rem;">
    <% @hobbies.each do |hobby| %>

      <div class="card-category">
        <div class="cad-title-name">
          <%= hobby.name %>
        </div>

        <div class="btns">
          <%= link_to "Join", hobby_path(hobby), class: "btn rounded-pill me-2 btn-outline-dark btn-sm mb-4" %>
          <% if current_user.admin? %>
            <%= link_to "Delete", hobby_path(hobby), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn rounded-pill me-2 btn-danger btn-sm mb-4" %>
          <% end %>
        </div>

      </div>

    <% end %>

  </div>


</div>

app/views/hobbies/new.html.erb
<div class="mx-auto" style="width: 800px;" >

  <div class="back-btn">
    <%= link_to "Back to Hobbies", hobbies_path(@hobbies), class: "btn btn-dark btn-sm mb-4" %>
  </div>

  <div class="form-hobby mt-4" style="width: 18rem;">
    <%= simple_form_for @hobby do |f| %>
    <%= f.input :name %>

    <%= f.simple_fields_for :chatroom do |chatroom| %>
      <%= chatroom.input :name, placeholder: 'Chatroom name' %>
    <% end %>
    <div class="btn btn-light btn-sm">
      <%= f.button :submit %>
    </div>
    <% end %>
  </div>

</div>

app/views/hobbies/show.html.erb
<div class="container">
  <div class="back-btn mt-4">
    <%= link_to "Back to Hobbies", hobbies_path(@hobbies), class: "btn rounded-pill me-2 btn-dark btn-sm mb-4" %>
  </div>

  <h1><%= @hobby.name %></h1>


  <div class="btns-show-bobbies" style="display: flex; justify-content:flex-start; align-items: center;">
    <div class="events-opt">
      <%# <%= link_to "See all events", hobby_events_path(@hobby, @events), class: "btn btn-light mt-4" %>
        <%= link_to "Add an event", new_hobby_event_path(@hobby, @event), class: "btn rounded-pill me-2 btn-outline-dark btn-sm" %>
    </div>


    <div class="chat-btn">
      <%= link_to "Join Chatroom", hobby_chatroom_path(@hobby, @hobby.chatroom), class: "btn rounded-pill me-2 btn-info btn-sm " %>
    </div>
  </div>


  <div class="event-list">

    <% @events.each do |event| %>
    <div class="mt-4 border-bottom border-dark" style="width: 250px;">
      <h5 class="title mt-3"><%= event.name %></h5>

      <h6><%= event.date.strftime("%A, %B %d") %></h6>

      <div class="event-btn">
        <%= link_to "See Details", hobby_event_path(event.hobby_id,event), class: "btn rounded-pill me-2 btn-dark btn-sm mb-4" %>


        <%# <%= link_to "Edit", edit_hobby_event_path(event.hobby_id, event), class: "btn btn-dark btn-sm mb-4" %>

        <%# <%= link_to "Delete", hobby_event_path(event.hobby_id, event), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger btn-sm mb-4" %>
      </div>

    </div>
    <% end %>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hobb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css", "pages/hobbies", "pages/_index", "application", "data-turbo-track": "reload", media: 'all' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div id="message-<%= message.id %>">
  <small>
    <strong><%= message.user.first_name %></strong>
    <i><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
  </small>
  <p><%= message.content %></p>
</div>

app/views/pages/home.html.erb
<div class="home-bg bg-white mb-4">
  <div class="header-title" style="width: 100%;  display: flex; justify-content: center; align-items: center;">
    <h1 class="mb-1 home-banner-title">UNLEASH YOUR PASSIONS</h1>
  </div>

  <div class="banner container mt-4" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1491438590914-bc09fcaaf77a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mzh8fGNvbW11bml0eXxlbnwwfHwwfHx8MA%3D%3D);">
    <div class="container container-home-banner" style="width: 90%;">
      <p class="mt-2 home-banner-des">Tired of generic social media? <strong>HOBB</strong> is the app that connects you with people who share your passions and ignites real-life adventures through exciting events.</p>
      <div class="join-btn home-banner-btn">
        <%= link_to "Join now", hobbies_path, class: "btn btn-outline-light rounded-pill" %>
      </div>
    </div>
  </div>

  <div class="container flex-container mt-4">
    <div class="head-title" style="width: 100%;">
      <h5>Forget <u>
        <i>
          endless scrolling
        </i>
        </u>. On <strong>HOBB</strong>, you:
      </h5>
    </div>

    <div class="row mt-4">
      <div class="card-container flex-container" style="height: 100%;">
        <div class="col">
          <div class="card h100 border-dark mb-3 rounded-4" style="width: 95%;">
            <div class="card-header border-dark">Discover a vibrant community</div>
            <div class="card-body">
              <p class="card-text">Explore hundreds of groups dedicated to everything from baking and birdwatching to coding and rock climbing.</p>
            </div>
          </div>
        </div>

        <div class="col">
          <div class="card h100 border-dark mb-3 rounded-4" style="width: 95%;">
            <div class="card-header border-dark">Find your tribe</div>
            <div class="card-body">
              <p class="card-text">Connect with like-minded individuals based on your shared interests.</p>
            </div>
          </div>
        </div>
      </div>

      <div class="card-container flex-container" style="height: 100%;">
        <div class="col">
          <div class="card h100 border-dark mb-3 rounded-4" style="width: 95%;">
            <div class="card-header border-dark">Dive into events</div>
            <div class="card-body">
              <p class="card-text">Join local workshops, attend meetups, and embark on thrilling experiences together.</p>
            </div>
          </div>
        </div>

        <div class="col">
          <div class="card h100 border-dark mb-3 rounded-4" style="width: 95%;">
            <div class="card-header bg-transparent border-dark">Spark meaningful connections</div>
            <div class="card-body">
              <p class="card-text">Go beyond likes and comments. Build genuine friendships and find your next adventure buddy.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="container mt-4 mb-4" style="width: 100%;">
    <div class="head-title" style=" display: flex; justify-content: center; align-items: center;">
      <h1 class="head-slogan"><strong>HOBB</strong> is more than just an app, it's a <em><u>movement!</u></em> </h1>
    </div>
  </div>


  <div class="container cards-container mb-4">
    <div class="card text-bg-dark rounded-4">
      <img src="https://images.unsplash.com/photo-1494809610410-160faaed4de0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cGVvcGxlJTIwZG9pbmclMjBhY3Rpdml0aWVzfGVufDB8fDB8fHww" class="card-img rounded-4" alt="...">
      <div class="card-img-overlay">
        <h5 class="card-title" style="text-shadow: 1px 1px 3px rgba(0,0,0,0.2);">Empowering self-expression</h5>
        <p class="card-text" style="text-shadow: 1px 1px 3px rgba(0,0,0,0.2);">Showcase your talents and passions through engaging profiles and event creations.</p>
      </div>
    </div>

    <div class="card text-bg-dark rounded-4">
      <img src="https://images.unsplash.com/photo-1520156557489-31c63271fcd4?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHBlb3BsZSUyMGhhdmluZyUyMGZ1bnxlbnwwfHwwfHx8MA%3D%3D" class="card-img rounded-4" alt="...">
      <div class="card-img-overlay">
        <h5 class="card-title" style="text-shadow: 1px 1px 3px rgba(0,0,0,0.2);">Celebrating diversity</h5>
        <p class="card-text" style="text-shadow: 1px 1px 3px rgba(0,0,0,0.2);">Embrace the richness of different interests and perspectives.</p>
      </div>
    </div>


    <div class="card text-bg-dark rounded-4">
      <img src="https://images.unsplash.com/photo-1582298538104-fe2e74c27f59?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjR8fHBlb3BsZSUyMGhhdmluZyUyMGZ1bnxlbnwwfDF8MHx8fDA%3D" class="card-img rounded-4" alt="...">
      <div class="card-img-overlay">
        <h5 class="card-title" style="text-shadow: 1px 1px 3px rgba(0,0,0,0.2);">Fostering real-world connections</h5>
        <p class="card-text" style="text-shadow: 1px 1px 3px rgba(0,0,0,0.2);">Break the screen barrier and create lasting memories in person.</p>
      </div>
    </div>
  </div>




  <div class="mt-4 mb-4">
    <div class="container col-sm-6 col-lg-4 mb-4 flex-container">

      <div class="card-home text-center bg-tansparent border-dark">
        <div class="card-body">
          <h5 class="card-title">"This app is a breath of fresh air! I love how it connects me with people who share my passions. I've already met some amazing people and participated in fun events."</h5>
        </div>
      </div>

      <div class="card-home text-center bg-tansparent border-dark">
        <div class="card-body">
          <h5 class="card-title">"HOBB is a great way to get out of your comfort zone and try new things. I finally signed up for that pottery class I've always wanted to take, thanks to an event I found on the app."</h5>
        </div>
      </div>

      <div class="card-home text-center bg-tansparent border-dark">
        <div class="card-body">
          <h5 class="card-title">"The app is easy to use and navigate. I love the clean interface and the vibrant colors. It makes finding events and connecting with people enjoyable."</h5>
        </div>
      </div>

    </div>


  </div>
  <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
    </div>
    <div class="footer-copyright">
      This footer is made with <i class="fas fa-heart"></i> at Le Wagon
    </div>
  </div>

</div>

app/views/reviews/index.html.erb
<div class="review-list">
  <div>
    <% @reviews.each do |review| %>
      <li><%= review.comment %></li>
    <% end %>
  </div>
</div>